
(in-package :cl-telebot)


(defclass bot ()
  ((token :initarg :token)
   (supports-inline-queries :reader bot-supports-inline-queries)
   (can-read-all-group-messages :reader bot-can-read-all-group-messages)
   (can-join-groups :reader bot-can-join-groups)
   (username :reader bot-username)
   (first-name :reader bot-first-name)
   (id :reader bot-id)
   (update-id :initform nil :accessor bot-update-id)))

(defclass echo-bot (bot) ())

(defgeneric on-update (bot update))


(defclass entity ()
  ((type :reader entity-type)
   (offset :reader entity-offset)
   (length :reader entity-length)
   (url :reader entity-url :initform nil)
   (text :reader entity-text)))

(defclass object ()
  ((id :reader object-id :initarg :id)))

(defclass user (object)
  ((first-name :reader user-first-name)
   (last-name :reader  user-last-name :initform nil)
   (username :reader user-username :initform nil)
   (language-code :reader user-language-code :initform nil)
   (is-bot :reader user-is-bot :initform nil)))

(defclass chat (object)
  ((type :reader chat-type)
   (title :reader chat-title :initform nil)
   (username :reader chat-username :initform nil)
   (first-name :reader chat-first-name :initform nil)
   (last-name :reader chat-last-name :initform nil)
   (all-members-are-administrators :reader chat-all-members-are-administrators :initform nil)))

(defclass message (object)
  ((from :reader message-from :initform nil)
   (date :reader message-date)
   (chat :reader message-chat)
   (forward-from :reader message-forward-from :initform nil)
   (forward-date :reader message-forward-date :initform nil)
   (reply-to-message :reader message-reply-to-message :initform nil)
   (edit-date :reader message-edit-date :initform nil)
   (text :reader message-text :initform nil)
   (entities :reader message-entities :initform nil)
   (audio :reader message-audio :initform nil)
   (document :reader message-document :initform nil)
   (photo :reader message-photo :initform nil)
   (sticker :reader message-sticker :initform nil)
   (video :reader message-video :initform nil)
   (voice :reader message-voice :initform nil)
   (caption :reader message-caption :initform nil)
   (contact :reader message-contact :initform nil)
   (location :reader message-location :initform nil)
   (venue :reader message-venue :initform nil)
   (new-chat-member :reader message-new-chat-member :initform nil)
   (left-chat-member :reader message-left-chat-member :initform nil)
   (new-chat-title :reader message-new-chat-title :initform nil)
   (new-chat-photo :reader message-new-chat-photo :initform nil)
   (delete-chat-photo :reader message-delete-chat-photo :initform nil)
   (group-chat-created :reader message-group-chat-created :initform nil)
   (supergroup-chat-created :reader message-supergroup-chat-created :initform nil)
   (channel-chat-created :reader message-channel-chat-created :initform nil)
   (migrate-to-chat-id :reader message-migrate-to-chat-id :initform nil)
   (migrate-from-chat-id :reader message-migrate-from-chat-id :initform nil)
   (pinned-message :reader message-pinned-message :initform nil)))

(defclass update (object)
  ((message :reader update-message :initform nil)
   (inline-query :reader update-inline-query :initform nil)
   (chosen-inline-result :reader update-chosen-inline-result :initform nil)
   (callback-query :reader update-callback-query :initform nil)))
   
